// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcyPQFKlijDws5Xaj-eehrcqnvRkZgBk',
    appId: '1:321347486738:web:4fa736745306949b7004cb',
    messagingSenderId: '321347486738',
    projectId: 'easacc-bcd2c',
    authDomain: 'easacc-bcd2c.firebaseapp.com',
    storageBucket: 'easacc-bcd2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt5ZCGNGVeUKvfyLKDzT99AhaTpHeuRLQ',
    appId: '1:321347486738:android:2cb59859cccb5f227004cb',
    messagingSenderId: '321347486738',
    projectId: 'easacc-bcd2c',
    storageBucket: 'easacc-bcd2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoeuymcY5HXHijdMDhxngnyGUyqzonc_M',
    appId: '1:321347486738:ios:3cf4d237931ecfe67004cb',
    messagingSenderId: '321347486738',
    projectId: 'easacc-bcd2c',
    storageBucket: 'easacc-bcd2c.firebasestorage.app',
    iosClientId: '321347486738-fl2l69rmqu96unc2s2d4ilha41tch500.apps.googleusercontent.com',
    iosBundleId: 'com.easacc.easaccTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoeuymcY5HXHijdMDhxngnyGUyqzonc_M',
    appId: '1:321347486738:ios:3cf4d237931ecfe67004cb',
    messagingSenderId: '321347486738',
    projectId: 'easacc-bcd2c',
    storageBucket: 'easacc-bcd2c.firebasestorage.app',
    iosClientId: '321347486738-fl2l69rmqu96unc2s2d4ilha41tch500.apps.googleusercontent.com',
    iosBundleId: 'com.easacc.easaccTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQcyPQFKlijDws5Xaj-eehrcqnvRkZgBk',
    appId: '1:321347486738:web:3b171888f39d495d7004cb',
    messagingSenderId: '321347486738',
    projectId: 'easacc-bcd2c',
    authDomain: 'easacc-bcd2c.firebaseapp.com',
    storageBucket: 'easacc-bcd2c.firebasestorage.app',
  );

}